name: Django testing abd deploy

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Check changes
        uses: actions/checkout@v2

      - name: install python3 
        uses: actions/setup-python@v2
          with:
            python-version: 3.10

      - name: install libraryes
        run: |
          pip install -r requirements.txt

      - name: Changes code on pep8
        run: flake8 main

      -name: Testing 
        run: python3 manage.py test