name: Django testing and deploy

on:
  push:
    branches: 
      - master

jobs:
  tests:  
    runs-on: ubuntu-22.04
    steps: 
      - name: Check changes
        uses: actions/checkout@v2

      - name: install python3 
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: 
          pip install -r requirements.txt

      - name: Checking code on pep8
        run: flake8 main

      -name: Run Tests 
        run: python3 manage.py test
